name: Bug Report
description: Report a bug in DiscRec
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open DiscRec
        2. Click record
        3. ...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: DiscRec version
      placeholder: e.g. 0.1.0
    validations:
      required: true
