name: Feature Request
description: Suggest a new feature for DiscRec
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
      placeholder: What problem does this solve for you?
    validations:
      required: false
